# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  mongodbtestapi:
    image: mongodbtestapi
    build:
      context: .
      dockerfile: MongoDbTest.API/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 80:80
      - 81:81
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
